void checkbalance(char *);
void transfermoney(void);
void Menu(void);
void show_det(char *);
void person(char *);
void login(void);
void login_suc(void);
void account(void);
void accountcreated(void);
void logout(void);
void bill(void);
void bill1(void);
void bill2(void);
void printMeals();
void orderMeals();
void orderMeals1();
double orderForPersonStat();
double orderForPerson();
void printStaters();